/**
 * Spotify Playlist Co-creation app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArtistObjectDTO } from './artistObjectDTO';
import { ImageObjectDTO } from './imageObjectDTO';


export interface AlbumObjectDTO { 
    /**
     * The artists of the album. Each artist object includes a link in `href` to more detailed information about the artist. 
     */
    artists: Array<ArtistObjectDTO>;
    /**
     * The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the album. 
     */
    id: string;
    /**
     * The name of the album. In case of an album takedown, the value may be an empty string. 
     */
    name: string;
    /**
     * The date the album was first released. 
     */
    release_date: string;
    /**
     * The cover art for the album in various sizes, widest first. 
     */
    images: Array<ImageObjectDTO>;
    /**
     * The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the album. 
     */
    uri: string;
}

