/**
 * Spotify Playlist Co-creation app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageObjectDTO { 
    /**
     * The source URL of the image. 
     */
    url: string;
    /**
     * The image height in pixels. 
     */
    height: number;
    /**
     * The image width in pixels. 
     */
    width: number;
}

