/**
 * Spotify Playlist Co-creation app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Properties of a session
 */
export interface SessionPropertiesDTO { 
    /**
     * Maximum number of songs a guest can add to queue
     */
    max_songs_per_guest?: number;
    /**
     * Maximum number of guests that can join the session
     */
    max_number_of_guests?: number;
    /**
     * Should explicit content be forbidden to be added to session
     */
    ban_explicit_content?: boolean;
    /**
     * List of banned genres
     */
    banned_genres?: Array<string>;
    /**
     * Should app generate and add to owners account playlist with all tracks that were added via session
     */
    generate_playlist?: boolean;
}

